version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: contacts
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    image: contacts-api
    environment:
      PG_PWD: mysecretpassword
      PG_HOST: db
      PG_DATABASE: contacts
      PG_USER: postgres
    depends_on:
      - db
    ports:
      - "4000:3000"
